name: cd for backend

on:
  push:
    branches:
      - Master
    paths:
      - "Backend/**"

jobs:
  dockerhub:
    name: Build, push to dockerhub

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/youtube-assistant-backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{env.DOCKERHUB_REPO}}:latest
