name: cd

on:
  push:
    branches:
      - Master

jobs:
  deploy:
    name: Update deployed images
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ./Projects/YT-Assistant
            ./deploy.sh
