name: cd

on:
  push:
    branches:
      - Master

jobs:
  deploy:
    name: Update deployed images
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run deployment script
        run: |
          cd ~/Projects/YT-Assistant
          chmod +x ./deploy.sh 
          ./deploy.sh
